AUTO_GENERATE_DIR := libgb/arch/generated
AUTO_GENERATE_SCRIPT := register_gen/generate_hpp.py
AUTO_GENERATE := python $(AUTO_GENERATE_SCRIPT)

AUTOGENERATED_HEADERS = \
	$(AUTO_GENERATE_DIR)/enums.hpp \
	$(AUTO_GENERATE_DIR)/accessors.hpp

.PHONY: default
default: $(AUTOGENERATED_HEADERS)

$(AUTO_GENERATE_DIR)/enums.hpp: register_gen/registers.json $(AUTO_GENERATE_SCRIPT)
	$(AUTO_GENERATE) $< -o $@ --type enum

$(AUTO_GENERATE_DIR)/accessors.hpp: register_gen/registers.json $(AUTO_GENERATE_SCRIPT)
	$(AUTO_GENERATE) $< -o $@ --type accessors
