BUILD_DIR := build
LIBGB_BUILD_DIR := $(BUILD_DIR)/libgb

CXX_OPTIONS := -Oz -g -std=c++26
CXX_OPTIONS += -Ilibgb/include

CXX := $(GB_TOOLCHAIN)/clang++ --target=gb-unknown-unknown

AUTO_GENERATE_DIR := libgb/include/libgb/arch/generated
AUTO_GENERATE_SCRIPT := register_gen/generate_hpp.py
AUTO_GENERATE := python $(AUTO_GENERATE_SCRIPT)

AUTOGENERATED_HEADERS := \
	$(AUTO_GENERATE_DIR)/enums.hpp \
	$(AUTO_GENERATE_DIR)/accessors.hpp

META := $(LIBGB_BUILD_DIR)/meta.o

.PHONY: default
default: $(AUTOGENERATED_HEADERS) $(META)

$(LIBGB_BUILD_DIR):
	mkdir -p $@

$(AUTO_GENERATE_DIR)/enums.hpp: register_gen/registers.json $(AUTO_GENERATE_SCRIPT)
	$(AUTO_GENERATE) $< -o $@ --type enum

$(AUTO_GENERATE_DIR)/accessors.hpp: register_gen/registers.json $(AUTO_GENERATE_SCRIPT)
	$(AUTO_GENERATE) $< -o $@ --type accessors

$(META): libgb/nintendo-logo.cpp | $(LIBGB_BUILD_DIR)
	$(CXX) $(CXX_OPTIONS) -fdata-sections -c $< -o $@
